import { readFileSync } from 'node:fs'
import { strict as assert } from 'node:assert'

const serverManager = readFileSync('android/app/src/main/java/com/codex/mobile/CodexServerManager.kt', 'utf8')
const permissionManager = readFileSync('android/app/src/main/java/com/codex/mobile/PermissionManagerActivity.kt', 'utf8')
const foregroundService = readFileSync('android/app/src/main/java/com/codex/mobile/CodexForegroundService.kt', 'utf8')
const setupScript = readFileSync('android/app/src/main/assets/setup-codex.sh', 'utf8')
const gradle = readFileSync('android/app/build.gradle.kts', 'utf8')
const workflow = readFileSync('.github/workflows/build-apk.yml', 'utf8')
const baselineScript = readFileSync('scripts/verify-openminis-baseline.sh', 'utf8')
const tsupConfig = readFileSync('tsup.config.ts', 'utf8')
const bundleScript = readFileSync('android/scripts/build-server-bundle.sh', 'utf8')
const packageJson = JSON.parse(readFileSync('package.json', 'utf8'))
const projectionSource = readFileSync('src/server/codexThreadProjection.mjs', 'utf8')
const appServerBridge = readFileSync('src/server/codexAppServerBridge.ts', 'utf8')

assert.match(serverManager, /private const val CODEX_VERSION = "0\.160\.0"/)
assert.match(serverManager, /model = "gpt-6\.1-sol"/)
assert.match(serverManager, /codex-code-mode-host/)
assert.doesNotMatch(serverManager, /private const val CODEX_VERSION = "0\.137\.0"/)

assert.match(setupScript, /CODEX_VERSION="0\.160\.0"/)
assert.match(setupScript, /@openai\/codex@\$\{CODEX_VERSION\}/)

assert.match(gradle, /versionCode = 362/)
assert.match(gradle, /versionName = "1\.0\.121-codex-cli-0\.160\.0-openminis-1\.12-safe-codex-updater-v362"/)
assert.match(gradle, /create\("operator"\)[\s\S]*applicationId = "com\.codex\.mobile\.pocketlobster\.test"/)
assert.match(workflow, /safe-codex-updater-v362-beta/)
assert.match(workflow, /versionCode='362'/)
assert.match(workflow, /PACKAGE_ID="com\.codex\.mobile\.pocketlobster\.beta"/)
assert.match(baselineScript, /versionCode = 362/)

assert.equal(packageJson.engines.node, '>=22.5.0')
assert.match(tsupConfig, /target: 'node22'/)
assert.match(tsupConfig, /external: \['express', 'commander', 'node:sqlite'\]/)
assert.match(bundleScript, /grep -Fq 'import\("sqlite"\)'/)
assert.match(bundleScript, /grep -Fq 'node:sqlite'/)
assert.match(workflow, /grep -F 'node:sqlite'/)
assert.match(workflow, /grep -Fq 'import\("sqlite"\)'/)
assert.match(projectionSource, /const NODE_SQLITE_MODULE = 'node:sqlite'/)
assert.match(projectionSource, /import\(NODE_SQLITE_MODULE\)/)

assert.match(serverManager, /codex-safe-update-/)
assert.match(serverManager, /CODEX_JS_SHA256/)
assert.match(serverManager, /verifyCodexAppServerInitialize/)
assert.match(serverManager, /verifyCodexModelAndToolHandshake/)
assert.match(serverManager, /snapshotCodexMutableState/)
assert.match(serverManager, /isCodexMutableStateFile/)
assert.match(serverManager, /failed to remove post-update state/)
assert.match(serverManager, /rollbackCodexUpdate/)
assert.match(serverManager, /recoverInterruptedCodexUpdate/)
assert.match(serverManager, /codex-update-journal\.json/)
assert.match(serverManager, /activated_unverified/)
assert.match(serverManager, /verifyActiveCodexHostHandshake/)
assert.match(permissionManager, /手动安全更新 Codex/)
assert.match(permissionManager, /serverManager\.installCodex/)
assert.doesNotMatch(permissionManager, /serverManager\.installPlatformBinary/)
assert.match(foregroundService, /isCodexSafeUpdateInProgress/)
assert.doesNotMatch(foregroundService, /installCodex/)
assert.match(appServerBridge, /providerId !== 'openai' && !selected/)
assert.match(appServerBridge, /providerId === 'openai'[\s\S]*runtimeStatus/)
assert.match(serverManager, /codex-\$CODEX_VERSION-linux-arm64\.tgz/)
assert.match(serverManager, /codex-cli \$CODEX_VERSION/)
assert.match(serverManager, /\$targetPkg\.staging/)
assert.doesNotMatch(serverManager, /Removing old Codex CLI/)
