import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

const read = (path) => readFile(new URL(`../${path}`, import.meta.url), 'utf8')

test('collaboration leader owns semantic routing through durable collaboration tools', async () => {
  const server = await read('src/server/codexAppServerBridge.ts')
  const minisTools = await read('android/openminis/src/main/java/com/openminis/app/integration/PocketLobsterCollaborationTools.kt')
  const claudeMcp = await read('android/app/src/main/assets/anyclaw/collaboration-mcp-server.js')
  const manager = await read('android/app/src/main/java/com/codex/mobile/CodexServerManager.kt')
  const minisTransform = await read('android/openminis/build.gradle.kts')
  const recoveryPolicy = await read('src/server/collaborationPolicy.js')
  const runtime = server.slice(server.indexOf('async function executeCollaborationRun'), server.indexOf('async function abortCollaborationRun'))
  assert.match(server, /runCodexCollaborationTurn/)
  assert.match(server, /runClaudeCollaborationTurn/)
  assert.match(server, /runMinisCollaborationTurn/)
  assert.match(server, /dynamicTools: collaborationDynamicToolSpecs\(\)/)
  assert.match(server, /codexCollaborationToolThreads/)
  assert.match(server, /Codex总调度线程缺少本进程的协作工具注册/)
  assert.match(server, /method === 'item\/tool\/call'/)
  assert.match(server, /collaboration_delegate_many/)
  assert.match(server, /collaboration_wait/)
  assert.match(server, /collaboration_followup/)
  assert.match(server, /collaboration_finish/)
  assert.match(server, /Collaboration tool call belongs to a stale or invalid turn/)
  assert.match(server, /Collaboration tool call belongs to an expired leader attempt/)
  assert.match(server, /每次协作工具调用都必须原样传入该turnNumber/)
  assert.match(server, /每次协作工具调用都必须原样传入该leaderLeaseId/)
  assert.match(server, /evidenceTaskIds must list every task created in the current turn/)
  assert.match(server, /deliveredToLeaderAtMs === null/)
  assert.match(server, /pendingUserMessages\.length > run\.presentedPendingMessageCount/)
  assert.match(server, /pendingUserMessages: \[\.\.\.run\.pendingUserMessages\]/)
  assert.match(server, /presentedPendingMessageCount/)
  assert.doesNotMatch(server, /pendingUserMessages: !wasInterrupted/)
  assert.match(server, /collaborationTaskExecutions/)
  assert.match(server, /reconcileInterruptedCollaborationRuns/)
  assert.match(server, /宿主不会使用关键词替您路由/)
  assert.doesNotMatch(runtime, /detectRequiredCollaborationTargets|buildRequiredCollaborationDecision|enforceRequiredCollaborationDecision/)
  assert.match(minisTools, /fun definitions\(\)/)
  assert.match(minisTools, /\.put\("callerAgentId", "minis"\)/)
  assert.match(minisTools, /val NAMES = setOf/)
  assert.match(minisTransform, /agentHistory\.any/)
  assert.match(minisTransform, /\[口袋大龙虾三智能体协作：总调度工具运行时\]/)
  assert.match(claudeMcp, /CALLER_AGENT_ID = "claude"/)
  assert.match(claudeMcp, /collaboration_finish/)
  assert.match(manager, /ensureCollaborationMcpConfig/)
  assert.match(manager, /anyclaw-toolbox-server\.cjs/)
  assert.match(manager, /pocket_collaboration/)
  assert.doesNotMatch(recoveryPolicy, /detectRequiredCollaborationTargets|enforceRequiredCollaborationDecision|INVOCATION_PATTERN/)
  assert.match(server, /chat\.prompt/)
  assert.match(server, /agent-sessions.*claude-code/s)
  assert.match(server, /turn\/interrupt/)
  assert.match(server, /chat\.session\.cancel/)
  assert.match(server, /await abortClaudeRun\(state\.runId\)/)
})

test('all three agent pages expose the collaboration switch and board', async () => {
  const app = await read('src/App.vue')
  const composer = await read('src/components/content/ThreadComposer.vue')
  const mainActivity = await read('android/app/src/main/java/com/codex/mobile/MainActivity.kt')
  const claudeLayout = await read('android/app/src/main/res/layout/activity_cli_agent_chat.xml')
  const minisTransform = await read('android/openminis/build.gradle.kts')
  assert.match(app, /CollaborationBoard/)
  assert.match(app, /listCollaborationRuns/)
  assert.match(app, /pocketlobster:\/\/collaboration/)
  assert.match(composer, /三智能体协作/)
  assert.match(composer, /aria-label="协作看板"/)
  assert.match(mainActivity, /pocketlobster:\/\/collaboration[\s\S]*CollaborationActivity/)
  assert.match(claudeLayout, /switchCliCollaboration/)
  assert.match(claudeLayout, /btnCliCollaborationBoard/)
  assert.match(minisTransform, /pocketLobsterCollaborationEnabled/)
  assert.match(minisTransform, /CollaborationClient\.startIfEnabled/)
})

test('shared Alpine sessions stay isolated while explicit browser tabs support agent handoff', async () => {
  const sharedCli = await read('android/app/src/main/assets/shared-runtime/shared-runtime-cli.js')
  const bridge = await read('android/openminis/src/main/java/com/openminis/app/integration/MinisRuntimeBridge.kt')
  const manager = await read('android/app/src/main/java/com/codex/mobile/CodexServerManager.kt')
  const claude = await read('android/app/src/main/java/com/codex/mobile/CliAgentChatActivity.kt')
  assert.match(sharedCli, /ANYCLAW_AGENT_ID/)
  assert.match(sharedCli, /agent_id: agentId/)
  assert.match(bridge, /browserTabsByAgent/)
  assert.match(bridge, /input\.tabId != null && pool\.tabs\.value\.none/)
  assert.match(bridge, /val requestedTab = input\.tabId/)
  assert.match(bridge, /call list_tabs and retry with an existing tab_id/)
  assert.doesNotMatch(bridge, /entries\.none \{ it\.key != normalizedAgentId/)
  assert.match(sharedCli, /Explicit shared tab handoff/)
  assert.match(bridge, /sessionId = "\$SHARED_SESSION_ID-\$\{normalizeAgentId\(agentId\)\}"/)
  assert.match(manager, /"ANYCLAW_AGENT_ID" to "codex"/)
  assert.match(claude, /"ANYCLAW_AGENT_ID" to "claude"/)
})

test('Claude task ownership survives page destruction and remains abortable', async () => {
  const activity = await read('android/app/src/main/java/com/codex/mobile/CliAgentChatActivity.kt')
  const registry = await read('android/app/src/main/java/com/codex/mobile/AgentTaskRegistry.kt')
  assert.doesNotMatch(activity, /if \(isFinishing\) \{\s*activeProcess\?\.destroy\(\)/s)
  assert.match(activity, /AgentTaskRegistry\.isRunning/)
  assert.match(activity, /AgentTaskRegistry\.abort/)
  assert.match(activity, /taskStatusHandler\.postDelayed\(this, 900L\)/)
  assert.match(registry, /process\.destroyForcibly/)
})

test('native collaboration clients wake the shared host and use the production port', async () => {
  const server = await read('src/server/codexAppServerBridge.ts')
  const service = await read('android/app/src/main/java/com/codex/mobile/CodexForegroundService.kt')
  const manager = await read('android/app/src/main/java/com/codex/mobile/CodexServerManager.kt')
  const nativeClient = await read('android/app/src/main/java/com/codex/mobile/CollaborationClient.kt')
  const minisClient = await read('android/openminis/src/main/java/com/openminis/app/integration/CollaborationClient.kt')
  const bundleScript = await read('android/scripts/build-server-bundle.sh')
  const workflow = await read('.github/workflows/build-apk.yml')
  const mainActivity = await read('android/app/src/main/java/com/codex/mobile/MainActivity.kt')
  const agentHub = await read('android/app/src/main/java/com/codex/mobile/AgentHubActivity.kt')
  assert.match(service, /START_STICKY/)
  assert.match(service, /ensureHostServer/)
  assert.match(service, /HEALTH_INTERVAL_MS/)
  assert.match(manager, /const val SERVER_PORT = 18923/)
  assert.match(manager, /fun isServerReady/)
  assert.match(manager, /managedServerProcess/)
  assert.match(manager, /POCKET_LOBSTER_SERVER_BUNDLE_ID/)
  assert.match(manager, /buildServerBundleVersion/)
  assert.match(manager, /context\.assets\.open\("server-bundle\/bundle-id"\)/)
  assert.match(manager, /installedBundleId == expectedBundleId/)
  assert.match(manager, /stagedBundleId == expectedBundleId/)
  assert.match(manager, /stagingDir\.renameTo\(targetDir\)/)
  assert.match(manager, /COLLABORATION_PROTOCOL_ID = "durable-agent-tools-v2"/)
  assert.match(manager, /fun describeServerHealth/)
  assert.match(manager, /Stopping previous server version[\s\S]*stopManagedServerProcess\(\)[\s\S]*Installing server bundle from APK/)
  assert.match(nativeClient, /CodexForegroundService\.ensureStarted/)
  assert.match(nativeClient, /repeat\(3\)/)
  assert.match(nativeClient, /host-api\/health/)
  assert.match(nativeClient, /instanceFollowRedirects = false/)
  assert.match(nativeClient, /contains\("application\/json"\)/)
  assert.match(nativeClient, /context\.assets\.open\("server-bundle\/bundle-id"\)/)
  assert.match(nativeClient, /collaborationProtocol/)
  assert.match(nativeClient, /claudeCollaborationReady/)
  assert.match(minisClient, /SERVER_PORT = 18923/)
  assert.match(minisClient, /HOST_SERVICE = "com\.codex\.mobile\.CodexForegroundService"/)
  assert.match(minisClient, /restorePrompt\(prompt\)/)
  assert.match(minisClient, /host-api\/health/)
  assert.match(minisClient, /instanceFollowRedirects = false/)
  assert.match(minisClient, /context\.assets\.open\("server-bundle\/bundle-id"\)/)
  assert.match(minisClient, /collaborationProtocol/)
  assert.match(minisClient, /claudeCollaborationReady/)
  assert.match(bundleScript, /ASSETS_DIR\/bundle-id/)
  assert.match(bundleScript, /BUNDLE_HASH/)
  assert.match(bundleScript, /find dist dist-cli -type f/)
  assert.match(bundleScript, /Embedded server bundle id/)
  assert.match(workflow, /Verify embedded server identity/)
  assert.match(workflow, /durable-agent-tools-v2/)
  assert.match(workflow, /claudeCollaborationReady/)
  assert.match(mainActivity, /BootstrapInstaller\.isBootstrapInstalled\(this\)[\s\S]*CodexForegroundService\.ensureStarted\(this\)[\s\S]*AgentHubActivity/)
  assert.match(agentHub, /CodexForegroundService\.ensureStarted\(this\)/)
  assert.match(service, /installServerBundle[\s\S]*isProxyReady[\s\S]*startServer/)
  assert.match(service, /ensureCollaborationRuntimeAssets\(\)[\s\S]*installServerBundle/)
  assert.match(service, /reportState\("ready", serverManager\.describeServerHealth\(\)\)/)
  assert.match(manager, /Claude collaboration MCP config verification failed/)
  assert.match(server, /function isClaudeCollaborationMcpReady/)
  assert.match(server, /claudeCollaborationReady: isClaudeCollaborationMcpReady\(\)/)
  assert.match(server, /Claude协作工具运行时尚未就绪/)
  assert.match(service, /三智能体协作宿主诊断\.jsonl/)
})

test('collaboration persistence, continuation, abort races and overload are guarded', async () => {
  const server = await read('src/server/codexAppServerBridge.ts')
  const policy = await read('src/server/collaborationPolicy.js')
  const app = await read('src/App.vue')
  assert.match(server, /COLLABORATION_TIMEOUT_MS = 6 \* 60 \* 60_000/)
  assert.match(server, /url\.pathname === '\/host-api\/health'/)
  assert.match(server, /SERVER_BUNDLE_ID/)
  assert.match(server, /readFileSync\(join\(dirname\(entryPath\), '\.\.', 'bundle-id'\)/)
  assert.match(server, /collaborationPersistQueue/)
  assert.match(server, /rename\(temporary, COLLABORATION_STATE_PATH\)/)
  assert.match(server, /isCollaborationRunAborted/)
  assert.match(server, /isCollaborationRunActive/)
  assert.match(server, /isMissingAgentSessionError/)
  assert.match(server, /ensureCodexCollaborationThread/)
  assert.match(server, /startCodexCollaborationTurnWithRecovery/)
  assert.match(server, /appServer\.rpc\('thread\/read', \{ threadId: candidateThreadId, includeTurns: false \}\)/)
  assert.match(server, /prepareThreadParams/)
  assert.match(server, /ensureCodexProviderDefinitions\(appServer\)/)
  assert.match(server, /buildInjectedDeveloperInstructions\(params\)/)
  assert.match(server, /appServer\.rpc\('thread\/resume', params\)/)
  assert.match(policy, /handlers\.startThread\(true\)/)
  assert.match(server, /Codex历史会话已失效，宿主已自动创建替代会话/)
  assert.match(server, /callMinisChatRpc\('chat\.sessions\.get', \{ sessionId \}\)/)
  assert.match(server, /Minis历史会话已失效，宿主已自动创建替代会话/)
  assert.match(server, /Claude Code本地协作历史缺失，宿主已按当前协作公开历史重建/)
  assert.match(server, /run\.pendingUserMessages = \[\]/)
  assert.match(server, /collaboration-api\/continue/)
  assert.match(server, /currentCollaborationTurnSnapshot/)
  assert.match(server, /archiveCurrentCollaborationTurn/)
  assert.match(server, /collaborationRunDetail/)
  assert.match(server, /url\.searchParams\.get\('turnNumber'\)/)
  assert.match(server, /turns: turnSnapshots/)
  assert.match(server, /pendingUserMessages/)
  assert.match(server, /补充指令：\$\{prompt\}/)
  assert.match(server, /tasks: CollaborationTask\[\]/)
  assert.match(server, /lastHeartbeatAtMs/)
  assert.match(server, /deliveredToLeaderAtMs/)
  assert.match(server, /collaboration-api\/delete/)
  assert.match(server, /collaboration-api\/archive/)
  assert.match(app, /document\.visibilityState !== 'visible'/)
  assert.match(app, /collaborationRuns\.value\.some\(isCollaborationRunActive\)/)
})

test('collaboration UI exposes public progress without internal routing payloads', async () => {
  const server = await read('src/server/codexAppServerBridge.ts')
  const board = await read('src/components/content/CollaborationBoard.vue')
  const nativeBoard = await read('android/app/src/main/java/com/codex/mobile/CollaborationActivity.kt')
  const normalizer = await read('src/api/normalizers/v2.ts')
  const minisTransform = await read('android/openminis/build.gradle.kts')
  const publicSummary = server.slice(
    server.indexOf('function collaborationRunSummary'),
    server.indexOf('export function createCodexBridgeMiddleware'),
  )
  assert.doesNotMatch(publicSummary, /sessionId|turnId|requestText/)
  assert.doesNotMatch(board, /requestText|sessionId|turnId/)
  assert.doesNotMatch(nativeBoard, /optString\("requestText"\)/)
  assert.match(board, /当前进展/)
  assert.match(board, /总调度/)
  assert.match(board, /协作成员/)
  assert.match(board, /继续协作/)
  assert.match(board, /补充指令/)
  assert.match(nativeBoard, /isActiveStatus/)
  assert.match(nativeBoard, /assignmentText/)
  assert.match(nativeBoard, /CollaborationClient\.continueRun/)
  assert.match(nativeBoard, /refreshOpenDetail/)
  assert.match(nativeBoard, /detailDialog\?\.isShowing/)
  assert.match(nativeBoard, /importantForAccessibility = View\.IMPORTANT_FOR_ACCESSIBILITY_YES/)
  assert.match(nativeBoard, /importantForAccessibility = View\.IMPORTANT_FOR_ACCESSIBILITY_NO/)
  assert.match(nativeBoard, /isScreenReaderFocusable = true/)
  assert.match(nativeBoard, /private data class AgentDetailViews/)
  assert.match(nativeBoard, /private fun createAgentDetailViews/)
  assert.match(nativeBoard, /private fun updateAgentDetailViews/)
  assert.match(nativeBoard, /views\.content\.visibility = if \(hasDetails && views\.expanded\)/)
  assert.match(nativeBoard, /"展开\$\{views\.label\}详情"/)
  assert.match(nativeBoard, /val orderedIds = listOf\("codex", "claude", "minis"\)\.filter \{ it != row\.leader \} \+ row\.leader/)
  assert.match(nativeBoard, /run\.optJSONArray\("selectedTasks"\)/)
  assert.match(nativeBoard, /selectedTasksForAgent\(run, id\)/)
  assert.doesNotMatch(nativeBoard, /"成员任务记录"/)
  assert.doesNotMatch(nativeBoard, /private data class TaskDetailViews/)
  assert.match(nativeBoard, /focusFinalSummary/)
  assert.match(nativeBoard, /leaderToggle\.announceForAccessibility\("总调度最终回复已更新"\)/)
  assert.match(nativeBoard, /focusContinuationControls/)
  assert.doesNotMatch(nativeBoard, /fullScroll\(View\.FOCUS_DOWN\)/)
  assert.match(nativeBoard, /input\.performAccessibilityAction\(AccessibilityNodeInfo\.ACTION_ACCESSIBILITY_FOCUS/)
  assert.match(nativeBoard, /text = "上一轮"/)
  assert.match(nativeBoard, /text = "下一轮"/)
  assert.match(nativeBoard, /CollaborationClient\.getRun/)
  assert.match(nativeBoard, /root\.addView\(scroll, LinearLayout\.LayoutParams\(LinearLayout\.LayoutParams\.MATCH_PARENT, 0, 1f\)\)/)
  assert.ok(
    nativeBoard.indexOf('root.addView(scroll') < nativeBoard.indexOf('root.addView(footer'),
    'continuation controls must live in a fixed footer outside the scrolling message area',
  )
  assert.match(nativeBoard, /ACTION_ACCESSIBILITY_FOCUS/)
  assert.match(nativeBoard, /text = "更多"/)
  assert.match(nativeBoard, /text = "导出"/)
  assert.match(nativeBoard, /text = "分享"/)
  assert.match(nativeBoard, /ActivityResultContracts\.CreateDocument\("application\/zip"\)/)
  assert.match(nativeBoard, /ZipOutputStream/)
  assert.match(nativeBoard, /"协作任务详情\.txt"/)
  assert.match(nativeBoard, /"协作任务原始记录\.json"/)
  assert.match(nativeBoard, /Intent\.ACTION_SEND/)
  assert.match(nativeBoard, /run\.optJSONArray\("events"\)/)
  assert.match(nativeBoard, /CollaborationClient\.exportRun/)
  assert.doesNotMatch(nativeBoard, /CollaborationClient\.archive/)
  assert.match(server, /collaboration-api\/export/)
  assert.match(server, /function collaborationRunExport/)
  assert.match(server, /selectedTasks: publicCollaborationTasksForTurn/)
  assert.doesNotMatch(nativeBoard, /content\.removeAllViews\(\)/)
  assert.doesNotMatch(nativeBoard, /accessibilityLiveRegion = View\.ACCESSIBILITY_LIVE_REGION_POLITE/)
  assert.ok(
    nativeBoard.indexOf('renderRunDetails(row)') < nativeBoard.indexOf('detailDialog = AlertDialog.Builder'),
    'detail nodes must be populated before the dialog is shown',
  )
  assert.ok(
    nativeBoard.indexOf('orderedIds.forEach') < nativeBoard.indexOf('val input = EditText'),
    'all three agent blocks, with the coordinator last, must stay above the continuation controls',
  )
  assert.match(board, /selectedRunId\.value\) \?\? null/)
  assert.doesNotMatch(board, /filteredRuns\.value\[0\]/)
  assert.match(normalizer, /extractCodexUserRequestText/)
  assert.match(normalizer, /isInternalCoordinatorPrompt/)
  assert.match(minisTransform, /Collaboration routing instructions remain in model context/)
  assert.match(minisTransform, /followsInternalCoordinatorPrompt/)
  assert.match(minisTransform, /if \(followsInternalCoordinatorPrompt\) return emptyList\(\)/)
  assert.match(minisTransform, /sessionTitle/)
})

test('deleting a collaboration run cleans its dedicated agent sessions', async () => {
  const server = await read('src/server/codexAppServerBridge.ts')
  assert.match(server, /cleanupCollaborationSessions/)
  assert.match(server, /thread\/archive/)
  assert.match(server, /chat\.session\.delete/)
  assert.match(server, /state\.sessions\.filter/)
  assert.match(server, /cleanupWarnings/)
})

test('collaboration files are created lazily and never used as the message bus', async () => {
  const server = await read('src/server/codexAppServerBridge.ts')
  const conversationManager = await read('android/app/src/main/java/com/codex/mobile/ConversationManagerActivity.kt')
  assert.match(server, /\/sdcard\/下载管理\/口袋大龙虾协作/)
  assert.match(server, /prepareCollaborationWorkspace/)
  assert.match(server, /if \(task\.requiresSharedWorkspace\)/)
  assert.match(server, /不承担智能体消息通信/)
  assert.match(server, /本轮未启用共享文件产物目录/)
  const startEndpoint = server.slice(server.indexOf("url.pathname === '/collaboration-api/start'"), server.indexOf("url.pathname === '/collaboration-api/continue'"))
  assert.doesNotMatch(startEndpoint, /prepareCollaborationWorkspace/)
  assert.match(conversationManager, /独立工作会话/)
  assert.match(conversationManager, /三智能体协作会话/)
  assert.doesNotMatch(conversationManager, /\$updated \| \$\{row\.id\}/)
})
