import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

const read = (path) => readFile(new URL(`../${path}`, import.meta.url), 'utf8')

test('collaboration coordinator routes through the leader before selectively invoking real agents', async () => {
  const server = await read('src/server/codexAppServerBridge.ts')
  assert.match(server, /runCodexCollaborationTurn/)
  assert.match(server, /runClaudeCollaborationTurn/)
  assert.match(server, /runMinisCollaborationTurn/)
  assert.match(server, /buildCollaborationCoordinatorPrompt/)
  assert.match(server, /parseCollaborationDecision/)
  assert.match(server, /buildCollaborationReviewPrompt/)
  assert.match(server, /COLLABORATION_MAX_DELEGATION_ROUNDS/)
  assert.match(server, /decision\.assignments\.map/)
  assert.match(server, /chat\.prompt/)
  assert.match(server, /agent-sessions.*claude-code/s)
  assert.match(server, /turn\/interrupt/)
  assert.match(server, /chat\.session\.cancel/)
})

test('all three agent pages expose the collaboration switch and board', async () => {
  const app = await read('src/App.vue')
  const composer = await read('src/components/content/ThreadComposer.vue')
  const mainActivity = await read('android/app/src/main/java/com/codex/mobile/MainActivity.kt')
  const claudeLayout = await read('android/app/src/main/res/layout/activity_cli_agent_chat.xml')
  const minisTransform = await read('android/openminis/build.gradle.kts')
  assert.match(app, /CollaborationBoard/)
  assert.match(app, /listCollaborationRuns/)
  assert.match(app, /pocketlobster:\/\/collaboration/)
  assert.match(composer, /三智能体协作/)
  assert.match(composer, /aria-label="协作看板"/)
  assert.match(mainActivity, /pocketlobster:\/\/collaboration[\s\S]*CollaborationActivity/)
  assert.match(claudeLayout, /switchCliCollaboration/)
  assert.match(claudeLayout, /btnCliCollaborationBoard/)
  assert.match(minisTransform, /pocketLobsterCollaborationEnabled/)
  assert.match(minisTransform, /CollaborationClient\.startIfEnabled/)
})

test('shared Alpine and browser calls are isolated by agent identity', async () => {
  const sharedCli = await read('android/app/src/main/assets/shared-runtime/shared-runtime-cli.js')
  const bridge = await read('android/openminis/src/main/java/com/openminis/app/integration/MinisRuntimeBridge.kt')
  const manager = await read('android/app/src/main/java/com/codex/mobile/CodexServerManager.kt')
  const claude = await read('android/app/src/main/java/com/codex/mobile/CliAgentChatActivity.kt')
  assert.match(sharedCli, /ANYCLAW_AGENT_ID/)
  assert.match(sharedCli, /agent_id: agentId/)
  assert.match(bridge, /browserTabsByAgent/)
  assert.match(bridge, /sessionId = "\$SHARED_SESSION_ID-\$\{normalizeAgentId\(agentId\)\}"/)
  assert.match(manager, /"ANYCLAW_AGENT_ID" to "codex"/)
  assert.match(claude, /"ANYCLAW_AGENT_ID" to "claude"/)
})

test('Claude task ownership survives page destruction and remains abortable', async () => {
  const activity = await read('android/app/src/main/java/com/codex/mobile/CliAgentChatActivity.kt')
  const registry = await read('android/app/src/main/java/com/codex/mobile/AgentTaskRegistry.kt')
  assert.doesNotMatch(activity, /if \(isFinishing\) \{\s*activeProcess\?\.destroy\(\)/s)
  assert.match(activity, /AgentTaskRegistry\.isRunning/)
  assert.match(activity, /AgentTaskRegistry\.abort/)
  assert.match(activity, /taskStatusHandler\.postDelayed\(this, 900L\)/)
  assert.match(registry, /process\.destroyForcibly/)
})

test('native collaboration clients wake the shared host and use the production port', async () => {
  const service = await read('android/app/src/main/java/com/codex/mobile/CodexForegroundService.kt')
  const manager = await read('android/app/src/main/java/com/codex/mobile/CodexServerManager.kt')
  const nativeClient = await read('android/app/src/main/java/com/codex/mobile/CollaborationClient.kt')
  const minisClient = await read('android/openminis/src/main/java/com/openminis/app/integration/CollaborationClient.kt')
  const bundleScript = await read('android/scripts/build-server-bundle.sh')
  const mainActivity = await read('android/app/src/main/java/com/codex/mobile/MainActivity.kt')
  const agentHub = await read('android/app/src/main/java/com/codex/mobile/AgentHubActivity.kt')
  assert.match(service, /START_STICKY/)
  assert.match(service, /ensureHostServer/)
  assert.match(service, /HEALTH_INTERVAL_MS/)
  assert.match(manager, /const val SERVER_PORT = 18923/)
  assert.match(manager, /fun isServerReady/)
  assert.match(manager, /managedServerProcess/)
  assert.match(manager, /POCKET_LOBSTER_SERVER_BUNDLE_ID/)
  assert.match(manager, /buildServerBundleVersion/)
  assert.match(manager, /fun describeServerHealth/)
  assert.match(manager, /Stopping previous server version[\s\S]*stopManagedServerProcess\(\)[\s\S]*Installing server bundle from APK/)
  assert.match(nativeClient, /CodexForegroundService\.ensureStarted/)
  assert.match(nativeClient, /repeat\(3\)/)
  assert.match(nativeClient, /host-api\/health/)
  assert.match(nativeClient, /instanceFollowRedirects = false/)
  assert.match(nativeClient, /contains\("application\/json"\)/)
  assert.match(minisClient, /SERVER_PORT = 18923/)
  assert.match(minisClient, /HOST_SERVICE = "com\.codex\.mobile\.CodexForegroundService"/)
  assert.match(minisClient, /restorePrompt\(prompt\)/)
  assert.match(minisClient, /host-api\/health/)
  assert.match(minisClient, /instanceFollowRedirects = false/)
  assert.match(bundleScript, /ASSETS_DIR\/bundle-id/)
  assert.match(bundleScript, /Embedded server bundle id/)
  assert.match(mainActivity, /BootstrapInstaller\.isBootstrapInstalled\(this\)[\s\S]*CodexForegroundService\.ensureStarted\(this\)[\s\S]*AgentHubActivity/)
  assert.match(agentHub, /CodexForegroundService\.ensureStarted\(this\)/)
  assert.match(service, /installServerBundle[\s\S]*isProxyReady[\s\S]*startServer/)
  assert.match(service, /三智能体协作宿主诊断\.jsonl/)
})

test('collaboration persistence, continuation, abort races and overload are guarded', async () => {
  const server = await read('src/server/codexAppServerBridge.ts')
  const app = await read('src/App.vue')
  assert.match(server, /COLLABORATION_TIMEOUT_MS = 2 \* 60 \* 60_000/)
  assert.match(server, /url\.pathname === '\/host-api\/health'/)
  assert.match(server, /SERVER_BUNDLE_ID/)
  assert.match(server, /readFileSync\(join\(dirname\(entryPath\), '\.\.', 'bundle-id'\)/)
  assert.match(server, /collaborationPersistQueue/)
  assert.match(server, /rename\(temporary, COLLABORATION_STATE_PATH\)/)
  assert.match(server, /isCollaborationRunAborted/)
  assert.match(server, /isCollaborationRunActive/)
  assert.match(server, /isMissingAgentSessionError/)
  assert.match(server, /appServer\.rpc\('thread\/read', \{ threadId, includeTurns: false \}\)/)
  assert.match(server, /prepareThreadParams/)
  assert.match(server, /ensureCodexProviderDefinitions\(appServer\)/)
  assert.match(server, /buildInjectedDeveloperInstructions\(params\)/)
  assert.match(server, /appServer\.rpc\('thread\/resume', params\)/)
  assert.match(server, /startReplacementThread\(true\)/)
  assert.match(server, /Codex历史会话已失效，宿主已自动创建替代会话/)
  assert.match(server, /callMinisChatRpc\('chat\.sessions\.get', \{ sessionId \}\)/)
  assert.match(server, /Minis历史会话已失效，宿主已自动创建替代会话/)
  assert.match(server, /Claude Code本地协作历史缺失，宿主已按当前协作公开历史重建/)
  assert.match(server, /run\.pendingUserMessages = \[\]/)
  assert.match(server, /pendingUserMessages: !wasInterrupted/)
  assert.match(server, /collaboration-api\/continue/)
  assert.match(server, /pendingUserMessages/)
  assert.match(server, /collaboration-api\/delete/)
  assert.match(server, /collaboration-api\/archive/)
  assert.match(app, /document\.visibilityState !== 'visible'/)
  assert.match(app, /collaborationRuns\.value\.some\(isCollaborationRunActive\)/)
})

test('collaboration UI exposes public progress without internal routing payloads', async () => {
  const server = await read('src/server/codexAppServerBridge.ts')
  const board = await read('src/components/content/CollaborationBoard.vue')
  const nativeBoard = await read('android/app/src/main/java/com/codex/mobile/CollaborationActivity.kt')
  const normalizer = await read('src/api/normalizers/v2.ts')
  const minisTransform = await read('android/openminis/build.gradle.kts')
  const publicSummary = server.slice(
    server.indexOf('function collaborationRunSummary'),
    server.indexOf('export function createCodexBridgeMiddleware'),
  )
  assert.doesNotMatch(publicSummary, /sessionId|turnId|requestText/)
  assert.doesNotMatch(board, /requestText|sessionId|turnId/)
  assert.doesNotMatch(nativeBoard, /optString\("requestText"\)/)
  assert.match(board, /当前进展/)
  assert.match(board, /总调度/)
  assert.match(board, /协作成员/)
  assert.match(board, /继续协作/)
  assert.match(board, /补充指令/)
  assert.match(nativeBoard, /isActiveStatus/)
  assert.match(nativeBoard, /assignmentText/)
  assert.match(nativeBoard, /CollaborationClient\.continueRun/)
  assert.match(nativeBoard, /refreshOpenDetail/)
  assert.match(nativeBoard, /detailDialog\?\.isShowing/)
  assert.match(nativeBoard, /importantForAccessibility = View\.IMPORTANT_FOR_ACCESSIBILITY_YES/)
  assert.match(nativeBoard, /importantForAccessibility = View\.IMPORTANT_FOR_ACCESSIBILITY_NO/)
  assert.match(nativeBoard, /isScreenReaderFocusable = true/)
  assert.match(nativeBoard, /private data class AgentDetailViews/)
  assert.match(nativeBoard, /setTextBlock\(views\.summaryHeading/)
  assert.match(nativeBoard, /private data class CollapsibleBlock/)
  assert.match(nativeBoard, /createCollapsibleBlock/)
  assert.match(nativeBoard, /setCollapsibleBlock\(agentViews\.assignment/)
  assert.match(nativeBoard, /setCollapsibleBlock\([\s\S]*agentViews\.response/)
  assert.match(nativeBoard, /"展开\$\{block\.label\}"/)
  assert.match(nativeBoard, /focusFinalSummary/)
  assert.match(nativeBoard, /focusContinuationControls/)
  assert.match(nativeBoard, /fullScroll\(View\.FOCUS_DOWN\)/)
  assert.match(nativeBoard, /input\.performAccessibilityAction\(AccessibilityNodeInfo\.ACTION_ACCESSIBILITY_FOCUS/)
  assert.match(nativeBoard, /ACTION_ACCESSIBILITY_FOCUS/)
  assert.match(nativeBoard, /text = "更多"/)
  assert.match(nativeBoard, /text = "导出"/)
  assert.match(nativeBoard, /text = "分享"/)
  assert.match(nativeBoard, /ActivityResultContracts\.CreateDocument\("application\/zip"\)/)
  assert.match(nativeBoard, /ZipOutputStream/)
  assert.match(nativeBoard, /"协作任务详情\.txt"/)
  assert.match(nativeBoard, /"协作任务原始记录\.json"/)
  assert.match(nativeBoard, /Intent\.ACTION_SEND/)
  assert.match(nativeBoard, /run\.optJSONArray\("events"\)/)
  assert.match(nativeBoard, /CollaborationClient\.exportRun/)
  assert.doesNotMatch(nativeBoard, /CollaborationClient\.archive/)
  assert.match(server, /collaboration-api\/export/)
  assert.match(server, /function collaborationRunExport/)
  assert.doesNotMatch(nativeBoard, /content\.removeAllViews\(\)/)
  assert.doesNotMatch(nativeBoard, /accessibilityLiveRegion = View\.ACCESSIBILITY_LIVE_REGION_POLITE/)
  assert.ok(
    nativeBoard.indexOf('renderRunDetails(row)') < nativeBoard.indexOf('detailDialog = AlertDialog.Builder'),
    'detail nodes must be populated before the dialog is shown',
  )
  assert.ok(
    nativeBoard.indexOf('val agentViews = linkedMapOf') < nativeBoard.indexOf('val summaryHeading = createText'),
    'agent progress must precede the final coordinator response',
  )
  assert.ok(
    nativeBoard.indexOf('val summary = createText') < nativeBoard.indexOf('val input = EditText'),
    'the final coordinator response must stay directly above the continuation controls',
  )
  assert.match(board, /selectedRunId\.value\) \?\? null/)
  assert.doesNotMatch(board, /filteredRuns\.value\[0\]/)
  assert.match(normalizer, /extractCodexUserRequestText/)
  assert.match(normalizer, /isInternalCoordinatorPrompt/)
  assert.match(minisTransform, /Collaboration routing instructions remain in model context/)
  assert.match(minisTransform, /followsInternalCoordinatorPrompt/)
  assert.match(minisTransform, /sessionTitle/)
})

test('deleting a collaboration run cleans its dedicated agent sessions', async () => {
  const server = await read('src/server/codexAppServerBridge.ts')
  assert.match(server, /cleanupCollaborationSessions/)
  assert.match(server, /thread\/archive/)
  assert.match(server, /chat\.session\.delete/)
  assert.match(server, /state\.sessions\.filter/)
  assert.match(server, /cleanupWarnings/)
})

test('collaboration files are created lazily and never used as the message bus', async () => {
  const server = await read('src/server/codexAppServerBridge.ts')
  const conversationManager = await read('android/app/src/main/java/com/codex/mobile/ConversationManagerActivity.kt')
  assert.match(server, /\/sdcard\/下载管理\/口袋大龙虾协作/)
  assert.match(server, /prepareCollaborationWorkspace/)
  assert.match(server, /if \(decision\.requiresSharedWorkspace\)/)
  assert.match(server, /不承担智能体消息通信/)
  assert.match(server, /本轮未启用共享文件产物目录/)
  const startEndpoint = server.slice(server.indexOf("url.pathname === '/collaboration-api/start'"), server.indexOf("url.pathname === '/collaboration-api/continue'"))
  assert.doesNotMatch(startEndpoint, /prepareCollaborationWorkspace/)
  assert.match(conversationManager, /独立工作会话/)
  assert.match(conversationManager, /三智能体协作会话/)
  assert.doesNotMatch(conversationManager, /\$updated \| \$\{row\.id\}/)
})
