import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const read = (path) => readFileSync(new URL(`../${path}`, import.meta.url), 'utf8')

const server = read('src/server/codexAppServerBridge.ts')
const gateway = read('src/api/collaborationGateway.ts')
const board = read('src/components/content/CollaborationBoard.vue')
const app = read('src/App.vue')
const collaborationActivity = read('android/app/src/main/java/com/codex/mobile/CollaborationActivity.kt')
const collaborationClient = read('android/app/src/main/java/com/codex/mobile/CollaborationClient.kt')
const collaborationLayout = read('android/app/src/main/res/layout/activity_collaboration.xml')
const conversationActivity = read('android/app/src/main/java/com/codex/mobile/ConversationManagerActivity.kt')
const conversationLayout = read('android/app/src/main/res/layout/activity_conversation_manager.xml')
const strings = read('android/app/src/main/res/values/strings.xml')
const openMinisBuild = read('android/openminis/build.gradle.kts')
const openMinisScreen = read('third_party/OpenMinis/src/android/app/src/main/java/com/openminis/app/ui/sessions/SessionListScreen.kt')
const openMinisViewModel = read('third_party/OpenMinis/src/android/app/src/main/java/com/openminis/app/ui/sessions/SessionListViewModel.kt')
const manager = read('android/app/src/main/java/com/codex/mobile/CodexServerManager.kt')
const controller = read('android/app/src/main/java/com/codex/mobile/ShizukuController.kt')
const shellBridge = read('android/app/src/main/java/com/codex/mobile/ShizukuShellBridgeServer.kt')
const promptStore = read('android/app/src/main/java/com/codex/mobile/PromptProfileStore.kt')

assert.match(server, /\/collaboration-api\/history\/clear/)
assert.match(server, /!isCollaborationRunActive\(run\) && run\.status !== 'waiting_user'/)
assert.match(server, /cleanupCollaborationSessions\(appServer, run\)/)
assert.match(gateway, /export async function clearCollaborationHistory/)
assert.match(app, /@clear-history="onClearCollaborationHistory"/)
assert.match(board, /aria-label="一键清空所有已结束和已归档的协作任务记录"/)
assert.match(board, /window\.confirm\(message\)/)
assert.match(collaborationClient, /fun clearHistory/)
assert.match(collaborationActivity, /运行中和等待您回复的任务不会被删除/)
assert.match(collaborationActivity, /永久删除\$\{count\}项/)
assert.match(collaborationLayout, /btnCollaborationClearHistory/)

assert.match(conversationActivity, /row\.workMode == WorkMode\.INDEPENDENT/)
assert.match(conversationActivity, /row\.source == SourceType\.CODEX \|\| row\.source == SourceType\.CLAUDE_CODE/)
assert.match(conversationActivity, /confirmClearIndependentConversations/)
assert.match(conversationLayout, /btnConversationClearIndependent/)
assert.match(strings, /conversation_clear_independent_message/)
assert.match(openMinisBuild, /fun deleteAllSessions\(\)/)
assert.match(openMinisBuild, /showClearAllDialog/)
assert.match(openMinisBuild, /enabled = sessions\.isNotEmpty\(\)/)
assert.match(openMinisBuild, /isDestructive = true/)
assert.match(openMinisScreen, /var showBulkDeleteDialog by remember \{ mutableStateOf\(false\) \}/)
assert.match(openMinisScreen, /sessionlist_shell_terminal/)
assert.match(openMinisViewModel, /private val _allSessions = MutableStateFlow/)
assert.match(openMinisViewModel, /fun deleteSession\(id: String\)/)

assert.match(controller, /126, 127 -> "command_unavailable"/)
assert.match(controller, /else -> "command_failed"/)
assert.match(shellBridge, /result\.errorCode == "command_failed" \|\| result\.errorCode == "command_unavailable"/)
assert.match(manager, /checked_at: checkedAt/)
assert.match(manager, /rg_local_ok: localRgExit === '0'/)
assert.match(manager, /rg_ubuntu_ok: ubuntuRgExit === '0'/)
assert.match(manager, /JSON\.stringify\(payload, null, 2\)/)
assert.doesNotMatch(manager, /const temporary = \\\`/)
assert.match(manager, /runtime-env-doctor\.sh" --probe --json/)
assert.match(promptStore, /rg_local_ok/)
assert.match(promptStore, /Verify command -v rg and rg --version/)

console.log('history, telemetry, and rg contract checks passed')
