import { createHash } from 'node:crypto'
import { readFileSync, statSync } from 'node:fs'
import { strict as assert } from 'node:assert'

const read = (path) => readFileSync(path, 'utf8')
const manifest = read('android/app/src/main/AndroidManifest.xml')
const runtime = read('android/app/src/main/java/com/codex/mobile/PhoneUiAgentRuntime.kt')
const activity = read('android/app/src/main/java/com/codex/mobile/PhoneUiAgentActivity.kt')
const overlay = read('android/app/src/main/java/com/codex/mobile/PhoneUiAgentProgressOverlay.kt')
const layout = read('android/app/src/main/res/layout/activity_phone_ui_agent.xml')
const protocol = read('android/app/src/main/java/com/codex/mobile/PhoneUiAgentProtocol.kt')
const modelManager = read('android/app/src/main/java/com/codex/mobile/PhoneUiAgentModelManagerActivity.kt')
const receiver = read('android/app/src/main/java/com/codex/mobile/PhoneUiShowerBinderReceiver.kt')
const bridge = read('android/app/src/main/java/com/codex/mobile/ShizukuShellBridgeServer.kt')
const toolbox = read('android/app/src/main/assets/anyclaw/claude-toolbox-server.js')
const minisTools = read('android/openminis/src/main/java/com/openminis/app/integration/PocketLobsterHostTools.kt')
const showerManager = read('android/showerclient/src/main/java/com/ai/assistance/showerclient/ShowerServerManager.kt')
const virtualCapture = read('android/app/src/main/java/com/codex/mobile/PhoneUiVirtualDisplayCapture.kt')
const showerController = read('android/showerclient/src/main/java/com/ai/assistance/showerclient/ShowerController.kt')
const shizukuController = read('android/app/src/main/java/com/codex/mobile/ShizukuController.kt')
const showerRenderer = read('android/showerclient/src/main/java/com/ai/assistance/showerclient/ShowerVideoRenderer.kt')
const showerServer = read('android/showerserver/src/main/java/com/ai/assistance/shower/Main.java')
const workflow = read('.github/workflows/build-apk.yml')
const openMinisBuild = read('android/openminis/build.gradle.kts')
const cliActivity = read('android/app/src/main/java/com/codex/mobile/CliAgentChatActivity.kt')

const sha256 = (value) => createHash('sha256').update(value).digest('hex')
assert.equal(sha256(runtime), '24ab561118cd988f7798518d4c2da9808a552a86c6be02b614b4358336e64938')
assert.equal(sha256(protocol), '5c711e856695a51e8280034ae0cccc26e3a0794efcb8f22e1404618ed82b68f7')
assert.equal(sha256(activity), '01963c83d5ffd769ae4cc424668304f529554922ba0c3f0671ba5d1406b3408a')
assert.equal(sha256(overlay), 'ef4b136384bd49ddbc49a0421429da079de5bed186c867b072a3ebec6db344dc')
assert.equal(sha256(layout), '9c078ca714bfba563cce26eccb496eb89fde510b8d72b5440f69cc9a9fba16d3')

assert.match(manifest, /android:name="\.PhoneUiAgentActivity"/)
assert.match(manifest, /android:name="\.PhoneUiAgentDisplayActivity"/)
assert.match(manifest, /android:name="\.PhoneUiAgentBootstrapActivity"/)
assert.match(manifest, /android\.permission\.SYSTEM_ALERT_WINDOW/)
assert.match(manifest, /android:name="\.PhoneUiShowerBinderReceiver"/)
assert.match(runtime, /VIRTUAL\("virtual"\)/)
assert.match(runtime, /requiresTakeover\(/)
assert.doesNotMatch(runtime, /terms = listOf\("支付"/)
assert.match(runtime, /startKeepAlive\(/)
assert.match(runtime, /PhoneUiVirtualDisplayCapture\.capturePng/)
assert.match(runtime, /resolveTaskTargetApp\(context, task\)/)
assert.match(runtime, /未向模型发送黑屏或替代截图/)
assert.doesNotMatch(runtime, /virtual-accessibility/)
assert.doesNotMatch(runtime, /virtual-shower-/)
assert.match(runtime, /executeShellCommandBinary\("screencap -p"\)/)
assert.match(runtime, /MinisAccessibilityService\.getInstance\(\)/)
assert.match(runtime, /主屏幕截图链路持续无有效画面/)
assert.match(runtime, /dumpsys input_method/)
assert.match(runtime, /mInputShown/)
assert.match(runtime, /mImeWindowVis/)
assert.match(runtime, /KEYCODE_BACK/)
assert.doesNotMatch(runtime, /repeatedActionCount/)
assert.doesNotMatch(runtime, /已阻止重复点击/)
assert.match(runtime, /modelActionResult\(decision\.action, executionResult, identicalActionStreak\)/)
assert.match(runtime, /动作未被宿主拦截/)
assert.match(runtime, /screenChangeHint\(priorScreenshot, screenshot\)/)
assert.match(runtime, /当前新截图相对动作前基本未变化/)
assert.match(runtime, /手指向上滑，通常显示页面更下方的内容/)
assert.match(protocol, /上一动作执行结果：\$actionResult/)
assert.match(protocol, /当前进度：第\$\{step\.coerceAtLeast\(1\)\}步/)
assert.match(protocol, /必须区分纵向页面滚动和横向栏目切换/)
assert.match(protocol, /绝不能机械重复到耗尽剩余步数/)
assert.match(protocol, /history\.takeLast\(24\)/)
assert.match(runtime, /buildFinalMessage/)
assert.match(runtime, /fun snapshot\(taskId: String\? = null\)/)
assert.match(runtime, /requireCurrentTaskLocked\(taskId\)/)
assert.match(runtime, /history\.optJSONObject/)
assert.match(runtime, /PhoneUiAgentProgressOverlay\.hideForCapture/)
assert.match(runtime, /PhoneUiAgentProgressOverlay\.restoreAfterCapture/)
assert.match(runtime, /虚拟屏幕原生H\.264视频流未产生可解码画面/)
assert.match(shizukuController, /fun executeShellCommandBinary/)
assert.match(virtualCapture, /ShowerSurfaceView/)
assert.match(virtualCapture, /TYPE_APPLICATION_OVERLAY/)
assert.match(showerController, /binaryHandlers/)
assert.match(showerController, /handlers\.forEach/)
assert.match(showerController, /videoConfigFrames/)
assert.match(showerController, /h264NalTypes/)
assert.match(showerRenderer, /splitAnnexbNalUnits/)
assert.match(showerServer, /codecConfig0/)
assert.match(showerServer, /PARAMETER_KEY_REQUEST_SYNC_FRAME/)
assert.match(showerServer, /BUFFER_FLAG_CODEC_CONFIG/)
assert.match(showerServer, /KEY_PREPEND_HEADER_TO_SYNC_FRAMES/)
assert.match(workflow, /patched-shower-classes\.dex/)
assert.match(workflow, /Unpatched upstream Shower server must not ship/)
assert.match(protocol, /AUTOGLM_NATIVE/)
assert.match(protocol, /GENERIC_JSON/)
assert.match(protocol, /"image_url"/)
assert.match(protocol, /callBody\(answer, "do"\)/)
assert.match(protocol, /连接与真实视觉生成均成功/)
assert.match(protocol, /Type完成后宿主会尝试自动收起输入法/)
assert.match(protocol, /finish的message必须用二到五句/)
assert.doesNotMatch(protocol, /登录、验证码、支付、发送、删除、安装、授权和隐私操作必须Take_over/)
assert.doesNotMatch(modelManager, /Spinner/)
assert.match(modelManager, /提供商预设，当前为/)
assert.match(receiver, /com\.ai\.assistance\.operit\.action\.SHOWER_BINDER_READY/)
assert.doesNotMatch(manifest, /PhoneUiShowerBinderReceiver"[\s\S]{0,120}android:permission="android\.permission\.DUMP"/)
assert.match(bridge, /isSharedRequestAuthorized/)
assert.match(toolbox, /application\/json; charset=utf-8/)
assert.match(minisTools, /application\/json; charset=utf-8/)
assert.doesNotMatch(toolbox, /phone_ui_agent_/)
assert.doesNotMatch(minisTools, /phone_ui_agent_/)
assert.doesNotMatch(openMinisBuild, /phoneAgentDefinitions/)
assert.doesNotMatch(cliActivity, /phone_ui_agent_/)
assert.doesNotMatch(bridge, /\/phone-agent\//)
assert.match(activity, /PhoneUiAgentRuntime\.startTask\(this, task, mode, maxSteps\)/)
assert.match(showerManager, />\$processLogPath 2>&1 <\/dev\/null &/)
assert.match(activity, /Settings\.ACTION_MANAGE_OVERLAY_PERMISSION/)
assert.match(layout, /btnPhoneUiOverlayPermission/)
assert.match(overlay, /TYPE_APPLICATION_OVERLAY/)
assert.match(overlay, /FLAG_NOT_TOUCHABLE/)
assert.doesNotMatch(activity, /announceForAccessibility/)
assert.doesNotMatch(overlay, /ACCESSIBILITY_LIVE_REGION/)
assert.doesNotMatch(layout, /accessibilityLiveRegion/)
assert.ok(statSync('android/showerclient/src/main/assets/shower-server.jar').size > 100_000)
