import { readFileSync, statSync } from 'node:fs'
import { strict as assert } from 'node:assert'

const read = (path) => readFileSync(path, 'utf8')
const manifest = read('android/app/src/main/AndroidManifest.xml')
const runtime = read('android/app/src/main/java/com/codex/mobile/PhoneUiAgentRuntime.kt')
const activity = read('android/app/src/main/java/com/codex/mobile/PhoneUiAgentActivity.kt')
const overlay = read('android/app/src/main/java/com/codex/mobile/PhoneUiAgentProgressOverlay.kt')
const layout = read('android/app/src/main/res/layout/activity_phone_ui_agent.xml')
const protocol = read('android/app/src/main/java/com/codex/mobile/PhoneUiAgentProtocol.kt')
const modelManager = read('android/app/src/main/java/com/codex/mobile/PhoneUiAgentModelManagerActivity.kt')
const receiver = read('android/app/src/main/java/com/codex/mobile/PhoneUiShowerBinderReceiver.kt')
const bridge = read('android/app/src/main/java/com/codex/mobile/ShizukuShellBridgeServer.kt')
const toolbox = read('android/app/src/main/assets/anyclaw/claude-toolbox-server.js')
const minisTools = read('android/openminis/src/main/java/com/openminis/app/integration/PocketLobsterHostTools.kt')
const showerManager = read('android/showerclient/src/main/java/com/ai/assistance/showerclient/ShowerServerManager.kt')
const virtualCapture = read('android/app/src/main/java/com/codex/mobile/PhoneUiVirtualDisplayCapture.kt')
const showerController = read('android/showerclient/src/main/java/com/ai/assistance/showerclient/ShowerController.kt')
const shizukuController = read('android/app/src/main/java/com/codex/mobile/ShizukuController.kt')
const showerRenderer = read('android/showerclient/src/main/java/com/ai/assistance/showerclient/ShowerVideoRenderer.kt')
const showerServer = read('android/showerserver/src/main/java/com/ai/assistance/shower/Main.java')
const workflow = read('.github/workflows/build-apk.yml')

assert.match(manifest, /android:name="\.PhoneUiAgentActivity"/)
assert.match(manifest, /android:name="\.PhoneUiAgentDisplayActivity"/)
assert.match(manifest, /android:name="\.PhoneUiAgentBootstrapActivity"/)
assert.match(manifest, /android\.permission\.SYSTEM_ALERT_WINDOW/)
assert.match(manifest, /android:name="\.PhoneUiShowerBinderReceiver"/)
assert.match(runtime, /VIRTUAL\("virtual"\)/)
assert.match(runtime, /requiresTakeover\(/)
assert.doesNotMatch(runtime, /terms = listOf\("支付"/)
assert.match(runtime, /startKeepAlive\(/)
assert.match(runtime, /PhoneUiVirtualDisplayCapture\.capturePng/)
assert.match(runtime, /resolveTaskTargetApp\(context, task\)/)
assert.match(runtime, /未向模型发送黑屏或替代截图/)
assert.doesNotMatch(runtime, /virtual-accessibility/)
assert.doesNotMatch(runtime, /virtual-shower-/)
assert.match(runtime, /executeShellCommandBinary\("screencap -p"\)/)
assert.match(runtime, /MinisAccessibilityService\.getInstance\(\)/)
assert.match(runtime, /主屏幕截图链路持续无有效画面/)
assert.match(runtime, /dumpsys input_method/)
assert.match(runtime, /mInputShown/)
assert.match(runtime, /mImeWindowVis/)
assert.match(runtime, /KEYCODE_BACK/)
assert.match(runtime, /repeatedActionCount >= 3/)
assert.match(runtime, /buildFinalMessage/)
assert.match(runtime, /fun snapshot\(taskId: String\? = null\)/)
assert.match(runtime, /requireCurrentTaskLocked\(taskId\)/)
assert.match(runtime, /history\.optJSONObject/)
assert.match(runtime, /PhoneUiAgentProgressOverlay\.hideForCapture/)
assert.match(runtime, /PhoneUiAgentProgressOverlay\.restoreAfterCapture/)
assert.match(runtime, /虚拟屏幕原生H\.264视频流未产生可解码画面/)
assert.match(shizukuController, /fun executeShellCommandBinary/)
assert.match(virtualCapture, /ShowerSurfaceView/)
assert.match(virtualCapture, /TYPE_APPLICATION_OVERLAY/)
assert.match(showerController, /binaryHandlers/)
assert.match(showerController, /handlers\.forEach/)
assert.match(showerController, /videoConfigFrames/)
assert.match(showerController, /h264NalTypes/)
assert.match(showerRenderer, /splitAnnexbNalUnits/)
assert.match(showerServer, /codecConfig0/)
assert.match(showerServer, /PARAMETER_KEY_REQUEST_SYNC_FRAME/)
assert.match(showerServer, /BUFFER_FLAG_CODEC_CONFIG/)
assert.match(showerServer, /KEY_PREPEND_HEADER_TO_SYNC_FRAMES/)
assert.match(workflow, /patched-shower-classes\.dex/)
assert.match(workflow, /Unpatched upstream Shower server must not ship/)
assert.match(protocol, /AUTOGLM_NATIVE/)
assert.match(protocol, /GENERIC_JSON/)
assert.match(protocol, /"image_url"/)
assert.match(protocol, /callBody\(answer, "do"\)/)
assert.match(protocol, /连接与真实视觉生成均成功/)
assert.match(protocol, /Type完成后宿主会尝试自动收起输入法/)
assert.match(protocol, /finish的message必须用二到五句/)
assert.doesNotMatch(protocol, /登录、验证码、支付、发送、删除、安装、授权和隐私操作必须Take_over/)
assert.doesNotMatch(modelManager, /Spinner/)
assert.match(modelManager, /提供商预设，当前为/)
assert.match(receiver, /com\.ai\.assistance\.operit\.action\.SHOWER_BINDER_READY/)
assert.doesNotMatch(manifest, /PhoneUiShowerBinderReceiver"[\s\S]{0,120}android:permission="android\.permission\.DUMP"/)
assert.match(bridge, /\/phone-agent\/start/)
assert.match(bridge, /isSharedRequestAuthorized/)
assert.match(bridge, /taskBase64/)
assert.match(bridge, /taskSha256/)
assert.match(bridge, /CodingErrorAction\.REPORT/)
assert.match(bridge, /put\("terminal", terminal\)/)
assert.match(bridge, /put\("nextPollAfterMs"/)
assert.match(bridge, /put\("eventCount"/)
assert.match(bridge, /put\("result"/)
assert.match(toolbox, /application\/json; charset=utf-8/)
assert.match(toolbox, /Buffer\.from\(normalizedTask, "utf8"\)/)
assert.match(toolbox, /phone_ui_agent_task_integrity_failed/)
assert.match(toolbox, /\["taskId"\]/)
assert.match(minisTools, /application\/json; charset=utf-8/)
assert.match(minisTools, /taskBase64/)
assert.match(minisTools, /taskBytes\.sha256\(\)/)
assert.match(minisTools, /required = listOf\("tool_title", "taskId"\)/)
for (const name of ['start', 'status', 'pause', 'resume', 'cancel']) {
  assert.match(toolbox, new RegExp(`tool\\("phone_ui_agent_${name}"`))
  assert.match(minisTools, new RegExp(`phone_ui_agent_${name}`))
}
assert.match(showerManager, />\$processLogPath 2>&1 <\/dev\/null &/)
assert.match(activity, /Settings\.ACTION_MANAGE_OVERLAY_PERMISSION/)
assert.match(layout, /btnPhoneUiOverlayPermission/)
assert.match(overlay, /TYPE_APPLICATION_OVERLAY/)
assert.match(overlay, /FLAG_NOT_TOUCHABLE/)
assert.match(overlay, /ACCESSIBILITY_LIVE_REGION_POLITE/)
assert.ok(statSync('android/showerclient/src/main/assets/shower-server.jar').size > 100_000)
